### PR TITLE
Add new docs structure

### PR DESCRIPTION
**Pull request by benraskin92**

### CODE REVIEW

**Comment by nerd0** [comment]
Mind explaining in the description how these documents will stay in sync with website?

**Comment by schallert** [comment]
LGTM x2

**Comment by CK-Ward** [comment]
LGTM, just a thought, have we thought about putting anything on the [Wiki](https://github.com/m3db/m3db/wiki)

**Comment by schallert** [comment]
> LGTM, just a thought, have we thought about putting anything on the Wiki

I hadn't thought of that. I think if our docs are comprehensive enough then they can hold "official" stuff, but maybe the wiki can be a place for less formal docs? Or maybe things more meta to the repo, like publishing docs and cutting releases. That seems to be what [prometheus](https://github.com/prometheus/prometheus/wiki) does.

**Pull request merged**
