### PR TITLE
Strip GOPATH from source path in auto-generated mocks

### PR DESCRIPTION
**Pull request by xichen2020**
cc @robskillington @martin-mao

### CODE REVIEW

**Comment by robskillington** [comment]
LGTM

**Comment by robskillington** [comment]
PS we probably need to do this for all our other repos too... or create an `m3build` repo and use as submodule.

**Comment by xichen2020** [comment]
Yeah although I don't think those even have build targets set up to automatically generate mocks so we'll need to add that first =]

**Comment by robskillington** [comment]
m3cluster I think has it?

**Comment by xichen2020** [comment]
Indeed, here is the PR to fix that as well: https://github.com/m3db/m3cluster/pull/13

**Pull request merged**
